const bottomTextArray = [
    "shares another reg link... again",
    "turns everything into a reg link",
    "forgets the reg link himself",
    "sends a reg link every 5 minutes",
    "dreams in reg links",
    "makes a reg link scavenger hunt",
    "turns a meme into a reg link",
    "names his cat 'Reg Link'",
    "puts a reg link on his coffee mug",
    "decorates with reg link posters",
    "accidentally sends a reg link to mom",
    "says 'reg link' more than 'hello'",
    "writes love letters with reg links",
    "turns homework into a reg link",
    "makes us sing the reg link song",
    "wears a 'Got Reg Links?' T-shirt",
    "creates reg link poetry",
    "hosts reg link trivia night",
    "decorates slides with reg links",
    "puts reg links in his email signature",
    "sends a reg link instead of a selfie",
    "introduces with a reg link",
    "puts reg links on business cards",
    "replaces 'please' with reg link",
    "signs off with 'regards and reg links'",
    "makes a reg link family tree",
    "adds reg links to his grocery list",
    "calls his pet fish Reg Link",
    "turns our names into reg links",
    "puts a reg link in his Wi-Fi password"
  ]
  